In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('IC_results_UPDATED.csv')

In [3]:
df_catalog = pd.read_csv('../../data_catalog/Qiuhan/Euclid_cats/filtered_lens_catalog_PL_IC_gt_70.csv')

In [4]:
df.head()

,target_index,pixel_scale,FWHM,R_E,r_s_eff,N_pix_expected,A_expected,max_snr_expected,IC_joint_expected,N_pix,A,max_snr,IC_joint,IC_nofactor
0,0,0.1,0.16,0.535876,0.340766,180,1.80,4.649510,110.570755,217,2.17,6.355067,133.299188,84.765625
1,1,0.1,0.16,0.898221,0.558383,229,2.29,2.696526,143.895255,255,2.55,5.466493,160.232708,99.609375
2,2,0.1,0.16,0.478011,0.214963,194,1.94,26.045172,168.513574,235,2.35,24.622487,204.127268,91.796875
3,3,0.1,0.16,0.626172,0.255094,202,2.02,13.132261,193.688833,252,2.52,12.149648,241.631613,98.437500
4,4,0.1,0.16,1.492396,0.163909,120,1.20,9.843766,426.798138,169,1.69,9.270092,601.074045,66.015625

In [5]:
filtered = df[df["IC_nofactor"] > 70]

In [6]:
filtered_in_catalog = df_catalog[df["IC_nofactor"] > 70]

In [7]:
filtered

,target_index,pixel_scale,FWHM,R_E,r_s_eff,N_pix_expected,A_expected,max_snr_expected,IC_joint_expected,N_pix,A,max_snr,IC_joint,IC_nofactor
0,0,0.1,0.16,0.535876,0.340766,180,1.80,4.649510,110.570755,217,2.17,6.355067,133.299188,84.765625
1,1,0.1,0.16,0.898221,0.558383,229,2.29,2.696526,143.895255,255,2.55,5.466493,160.232708,99.609375
2,2,0.1,0.16,0.478011,0.214963,194,1.94,26.045172,168.513574,235,2.35,24.622487,204.127268,91.796875
3,3,0.1,0.16,0.626172,0.255094,202,2.02,13.132261,193.688833,252,2.52,12.149648,241.631613,98.437500
6,6,0.1,0.16,0.477294,0.476440,270,2.70,10.527801,105.657803,310,3.10,11.347228,121.310810,121.093750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2452,2452,0.1,0.16,1.250894,0.340747,185,1.85,12.918931,265.289853,280,2.80,13.802846,401.519777,109.375000
2454,2454,0.1,0.16,0.617881,0.126337,150,1.50,80.202229,286.567516,204,2.04,80.676881,389.731822,79.687500
2456,2456,0.1,0.16,0.572721,0.335875,139,1.39,7.367714,92.585007,184,1.84,9.244980,122.558570,71.875000
2457,2457,0.1,0.16,0.856578,0.357832,175,1.75,10.466296,163.638398,252,2.52,10.273152,235.639293,98.437500
2460,2460,0.1,0.16,0.856864,0.226764,204,2.04,8.147399,301.112586,250,2.50,9.448792,369.010522,97.656250

In [8]:
filtered_in_catalog

,deflector_ra,deflector_dec,deflector_z,deflector_q,deflector_pa,deflector_vdisp,deflector_rband_abs_mag,deflector_Re,deflector_thetaE,deflector_thetaE_autolens,...,source_app_mag_r,source_app_mag_i,source_app_mag_z,IC_Euclid,IC_CSST,IC_Roman,IC_nofactor_Euclid,IC_nofactor_CSST,IC_nofactor_Roman,origin_batch
0,18.765015,0.519344,0.612120,0.790645,263.194819,228.748060,-22.853323,0.638501,0.535876,0.538893,...,24.859139,24.612931,24.156885,139.609299,107.140921,374.900774,88.281250,67.750032,237.066650,R1
1,7.384974,13.217773,0.641341,0.833568,88.785537,315.199528,-24.428088,1.021829,0.898221,0.920327,...,24.490169,23.971982,23.307421,175.121376,0.000000,877.628905,106.250000,0.000000,532.476807,R1
2,6.554591,1.669725,1.117882,0.816296,145.348020,265.846351,-23.611113,0.524361,0.478011,0.448648,...,24.024455,24.003017,23.942846,269.853936,631.972622,582.636863,129.296875,302.801161,279.162598,R1
3,10.330458,7.298118,1.019449,0.782827,282.979657,214.256020,-22.550807,0.488209,0.626172,0.639331,...,24.630808,24.469356,24.383268,189.927078,207.916902,531.217594,75.781250,82.959222,211.956787,R1
6,16.513213,10.998548,0.593589,0.761537,349.956812,180.257501,-21.894441,0.403036,0.477294,0.494989,...,23.287615,22.944831,22.862946,116.879957,167.350444,301.540398,112.500000,161.079157,290.240479,R1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2452,15.131210,3.804275,0.379122,0.575450,155.060819,252.266642,-23.462695,1.168367,1.250894,1.137280,...,25.353245,24.797901,24.229633,335.064917,297.652089,2915.989626,100.390625,89.181164,873.675537,R20
2454,13.726769,15.360649,0.351816,0.656269,168.333463,204.812522,-22.426800,0.341473,0.617881,0.626904,...,22.314322,21.331492,20.779740,876.132666,1708.378795,2568.945272,176.562500,344.280773,517.706299,R20
2456,18.136836,14.552643,0.534812,0.876634,7.217162,210.540293,-22.444841,0.482696,0.572721,0.579049,...,24.160308,23.759522,23.014735,202.704945,407.612360,435.441031,117.578125,236.433784,252.575684,R20
2457,14.456423,11.679886,0.670980,0.629729,293.470879,230.803599,-22.957434,0.257513,0.856578,0.859558,...,24.355301,24.377943,24.301252,197.987603,182.671847,942.009884,82.421875,76.045954,392.156982,R20
2460,7.799657,14.505096,1.055451,0.786143,344.921621,287.166011,-24.054438,0.492006,0.856864,0.848507,...,24.984803,24.818031,24.627514,425.338859,569.099423,1202.089286,113.671875,152.091908,321.258545,R20

In [9]:
print(len(filtered))

1391

In [10]:
len(filtered)/len(df)

0.5647584246853431

only 56% passes the criterea nofactor > 70 criterea